---
- hosts: [staging]
  become: true
 
  vars:
    dir: "weight-tracker-app"   
    mydir: "home/majdoleen/weight-tracker-app"

  vars_files:
    "roles/common/vars/main.yml"
  roles:
    - role: common
